### ISSUE TITLE
you can spawn at your other characters last location

### ISSUE THREAD

**Issue by Alokas123** [Qbox-project/qbx_spawn#17]
### Summary

you can spawn at your other characters last location

### Reproduction

1. log to your character
2. /logout
3. select other character
4. now there is 2 last locations for your current character and old

### Expected behavior

able to spawn at your characters last location

### Actual behavior

able to spawn at your characters last location and your other character last location

### Current Version

1.0.0

### Custom Resources

only hud

**Comment by artur-michalak** [comment]
fix almost ready

**Comment by Alokas123** [comment]
> fix almost ready

thank you!
