### ISSUE TITLE
Last Location not working

### ISSUE THREAD

**Issue by Jordan-Cache** [Qbox-project/qbx_spawn#9]
### Summary

The last location spawn option is not working, it spawns randomly

### Reproduction

I have the top option of server artifacts. This is a fresh build as per your raw link in your discord. Created my character, logged out and quit the game and respawned in on top of the skyscraper which is definitely not where i was.

### Expected behavior

To be spawned at my last location in the city

### Actual behavior

Spawned on top of the skyscraper/crane

### Last Updated

Today

### Custom Resources

None

### Resource Rename

no

**Comment by BigSmoKe07** [comment]
whats your player update interval?

**Comment by Jordan-Cache** [comment]
> whats your player update interval?

Where would I find this?

**Comment by mafewtm** [comment]
Doesnt seem to be an issue any longer.
